### ISSUE TITLE
Retrieve package from cache fails

### ISSUE THREAD

**Issue by luciobordonaro** [melfore/mosaic#12]
Retrieve package from cache fails as documented by following steps:
- https://github.com/melfore/mosaic/runs/539532831?check_suite_focus=true
- https://github.com/melfore/mosaic/runs/539410081?check_suite_focus=true

Seems like cache is not restored successfully.
Investigate to find out if a solution exists (maybe installing other actions packages).

For the moment the step to restore from cache the dependencies is commented out

```
    # Cache layer for project dependencies
    - name: Cache Dependencies
      id: cache-dependencies
      uses: actions/cache@v1
      env:
        cache-name: mosaic-dependencies
      with:
        path: ~/.npm
        key: ${{ runner.os }}-package-lock-${{ hashFiles('**/package-lock.json') }}

    # Install project dependencies
    - name: Install Dependencies
      # if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: npm ci
```

In this way it seems like no cache is applied and `npm ci` is restarted every time from scratch.
